@startuml
skinparam classAttributeIconSize 0

'=========================
' Classes de domínio
'=========================

abstract class Usuario {
    -id: UUID
    -nome: String
    -email: String
    -senhaHash: String

    +autenticar()
}

class Cliente {
    +realizarReserva()
    +cancelarReserva()
    +avaliarHospedagem()
}

Usuario <|-- Cliente

class Hospedagem {
    -id: UUID
    -nome: String
    -endereco: String
    -descricao: String
    -tipoQuarto: TipoQuarto
    -valorDiaria: Double
    -notaMedia: Double

    +calcularNotaMedia()
}

class Reserva {
  -id: UUID
  -dataCheckin: Date
  -dataCheckout: Date
  -valorTotal: Decimal
  -status: StatusReserva

  +confirmar()
  +cancelar()
  +calcularValor()
  +verificarDisponibilidade()
}

class TipoQuarto {
  id: UUID
  nome: String
}

class Pagamento {
  -id: UUID
  -valor: Decimal
  -dataPagamento: DateTime
  -status: StatusPagamento

  +aprovar()
  +reembolsar()
}

class Avaliacao {
  -id: UUID
  -nota: Integer
  -comentario: String
  -dataCriacao: Date

  +publicar()
}

class PoliticaCancelamento {
    -prazoHoras: Integer
    -percentualReembolso: Double

    +validarCancelamento()
    +calcularReembolso()
}

'=========================
' Interfaces
'=========================

interface GatewayPagamento {
    +processarPagamento()
    +processarReembolso()
}

interface ServicoEmail {
    +enviarConfirmacao()
}

Pagamento ..> GatewayPagamento
Reserva ..> ServicoEmail

'=========================
' Enumerações
'=========================

enum StatusReserva {
  PENDENTE
  CONFIRMADA
  CANCELADA
  CONCLUIDA
}

enum StatusPagamento {
  PENDENTE
  APROVADO
  REEMBOLSADO
  RECUSADO
}

'=========================
' Relacionamentos
'=========================

Cliente "1" --> "0..*" Reserva : Realiza

Reserva "1" *-- "1" Pagamento

Reserva "1" --> "1" PoliticaCancelamento

Hospedagem "1" --> "0..*" Avaliacao
Reserva "1" --> "1" Avaliacao

Hospedagem "1..*" *-- "1" TipoQuarto
Hospedagem "1" --* "0..*" Reserva

@enduml
